services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: unless-stopped
    networks:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama-webui:
    image: ollama-webui:latest
    container_name: ollama-webui
    build:
      context: ./open-webui/
      args:
        OLLAMA_API_BASE_URL: '/ollama/api'
      dockerfile: Dockerfile
    depends_on:
      - ollama
      - stable-diffusion
    ports:
      - 3000:8080
    environment:
      - ENABLE_OLLAMA_API=true
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_IMAGE_GENERATION=true
      - AUTOMATIC1111_BASE_URL=http://stable-diffusion:7860
      - IMAGE_SIZE=800x600
      - IMAGE_STEPS=3
    restart: unless-stopped
    networks:
      - ollama

  stable-diffusion:
    image: goolashe/automatic1111-sd-webui
    container_name: stable-diffusion
    networks:
      - ollama
    restart: unless-stopped
    environment:
      - CLI_ARGS=--no-half --allow-code --medvram --xformers --enable-insecure-extension-access --api
      - PYTHONUNBUFFERED="1"
      - TERM="vt100"
      - SD_WEBUI_VARIANT="default"
    ports:
      - 4000:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  ollama:
    name: ollama
